### PR TITLE
new features

### PR DESCRIPTION
**Pull request by Lkleven**
Database in which suggestions will be saved is not yet implemented. Everything is mock-data.

Kind of a large PR just to get "things up and running"

* Changed appearance to be much brighter and cleaner looking
* Added checbox "All". This is default when page is loaded as all categories will be displayed
* Clicking like on a suggestion will increase its like-count by +1 and highlight a heart to indicate this. If like is clicked again, +1 will be removed.
* CSS colors moved to vars, exception for named colors such as "white"
* Improved(?) names of functions

### CODE REVIEW

**Comment by asbjornh** [comment]
It's good to provide a description of what the PR will add!

**Comment by Lkleven** [comment]
Updated. 
Future PR's will be smaller and more specific now that there will be something to build on.

**Review by asbjornh — COMMENTED** [review]
~There's warnings when running `yarn dev`~

LOL I was on the `master` branch

**Comment by asbjornh** [comment]
~Other than the warnings, it seems to work fine! :)~

Disregard this. Wrong branch...

**Review by asbjornh — APPROVED** [review]
Looks much nicer now 👍

**Pull request merged**
